### ISSUE TITLE
External sensor

### ISSUE THREAD

**Issue by reivis** [schroepfer/CubeCell-LoraWan-DS18B20#2]
I bought this external sensor.

https://nl.aliexpress.com/item/4000550061662.html?spm=a2g0o.order_list.order_list_main.17.23d779d2GGTqFT&gatewayAdapt=glo2nld

But after soldering it I got no temperature reading.
I have used the resistor between VCC and Ground.
Because it's the same sensor it had to work wright?

Edit: I was to fast with writing........ External sensor also works.

**Comment by schroepfer** [comment]
No, the Resistor must soldered between VCC and the output of the sensor DS18B20.
(yellow and red)
